# 1. Distance 

In [1]:
import pandas as pd 
import numpy as np
from scipy.spatial import distance_matrix

In [ ]:
# Mocking Data   
# Dictionary 
data = { 
    "ID": [ "P1", "P2", "P3", "P4"],
    "x": [0, 2, 3, 5],
    "y": [2, 0, 1, 1],
}

In [ ]:
# แปลง Dictionary to DataFrame 
df = pd.DataFrame(data).set_index("ID")
df

In [17]:
# manhattan 
manhattan = distance_matrix( df.values, df.values, p=1)
manhattan = pd.DataFrame( manhattan, index=df.index, columns=df.index)
# Euclidian 
euclidian = distance_matrix( df.values, df.values, p = 2  )
# minkowsky p = 3
minkowsky = distance_matrix( df.values, df.values, p = 3    )

In [18]:
print( "manhattan \n"  ,manhattan.round(3))
print("euclidian \n", euclidian.round(3))
print("minkowsky \n", minkowsky.round(3))

manhattan 
 ID   P1   P2   P3   P4
ID                    
P1  0.0  4.0  4.0  6.0
P2  4.0  0.0  2.0  4.0
P3  4.0  2.0  0.0  2.0
P4  6.0  4.0  2.0  0.0
euclidian 
 [[0.    2.828 3.162 5.099]
 [2.828 0.    1.414 3.162]
 [3.162 1.414 0.    2.   ]
 [5.099 3.162 2.    0.   ]]
minkowsky 
 [[0.    2.52  3.037 5.013]
 [2.52  0.    1.26  3.037]
 [3.037 1.26  0.    2.   ]
 [5.013 3.037 2.    0.   ]]
