## Installing and Import Numpy

In [2]:
# Installing numpy 
# pip install numpy 
# import numpy 
import numpy as np

## 1. Array creation

การสร้างอาเรย์ด้วย NumPy มีหลายวิธี เช่น `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`

In [ ]:
# 1 - dimensiona1 array 1,5,2,0 
arr_1d = np.array([ 1, 5, 2, 0 ])
# 2 - dimensional array  1,5,2,0  8,3,6,1  1,7,2,9
arr_2d = np.array([ [1,5,2,0], [8,3,6,1], [1,7,2,9] ])

# 3 - dimensional array 10, 15, 20, 25   30, 35, 40, 45   50, 55, 60, 65 
arr_3d = np.array([ [10, 15], 
                [ 20, 25], 
                
                [30, 35], 
                [40, 45],
                
                [50, 55], 
                [60, 65] ])

# สร้างอาเรย์จากลิสต์
a = np.array([1, 2, 3])

# อาเรย์ค่า 0
b = np.zeros((2,3))

# อาเรย์ค่า 1
c = np.ones((3,3))

# อาเรย์ช่วงตัวเลข
d = np.arange(0,10,2)

# อาเรย์ค่าที่แบ่งช่วงเท่าๆกัน
e = np.linspace(0,1,5) 

# อาเรย์ 1Dimension  
f = np.array([ 1, 2, 3, 4])

# อาเรย์ 2Dimension  
g = np.array([  [ 1, 2, 3, 4], [5, 6, 7, 8] ])

# output

# print("a =", a)
# print("b =", b)
# print("c =", c)
# print("d =", d)
# print("e =", e)
# print("f =", f)
# print("g =", g)

In [10]:
print(arr_1d)
print(arr_2d)
print(arr_3d)

[1 5 2 0]
[[1 5 2 0]
 [8 3 6 1]
 [1 7 2 9]]
[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]
 [60 65]]


## 2. Array Fundametals 

      2.1 Slicing

In [ ]:
default_array = np.array([1,2,3,4,5,6])
default_array_2d = np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12] ])

In [ ]:
# สามตัวแรก 
default_array[ :3]

# ตีวที่ 4 เป็นต้นไป 
default_array[3:]

# สามชืกใน row 2 columns 4 
default_array_2d[1,3]

8


## 3. Array attribute 

ndim   จำนวนมิติของ Array  // row and column 

shape  จำนวนของ row and column  (r, c)

size  จำนวนสมาชิกใน array  (r*c)

dtype ชนิดข้อมูล 

In [19]:
array_attribute = np.array([ [  1, 2, 3, 4 ], [  5, 6, 7, 8 ], [ 9, 10, 11, 12 ] ])


In [ ]:
# array_attribute.ndim
# array_attribute.shape
# array_attribute.size
# array_attribute.dtype

dtype('int64')

## 4. Basics Array

np.zeros(dim) สร้าง Array ทีมี่สมาชิกเป็น 0  dim กำหนดมิติ 
ืnp.ones(dim)  สร้าง Array ทีมี่สมาชิกเป็น 1  dim กำหนดมิติ 
np.full(Z)   สร้าง Array ทีมี่สมาชิกเป็นจำนวนที่กำหนด Z
np.arrang(n) สร้าง Array ที่มีสมาชิกเริ่มที่ 0 ถึง n 

In [39]:
zero_2d_array = np.zeros(2)
one_1d_array = np.ones(5)
arang_array = np.arange(4)
step_arang_array= np.arange(2,9,2)  # start stop step 

In [40]:
# zero_2d_array
# one_1d_array
# arang_array
# step_arang_array
print(one_1d_array)

[1. 1. 1. 1. 1.]


## 4. Basic array operators 

+-*/ 

In [ ]:
data = np.array([ 1, 2])
ones = np.ones(2)# [1, 1 ]
b = np.array([ [1,1], [2,2] ])  
# [ 1, 1 ]  
# [ 2, 2 ]

In [64]:
sum = data + ones  
diff = data - ones 
multiply_array = data * ones 
divide_array = data/ones
col_sum = b.sum(axis=0) # ผลรวมแนว column
row_sum= b.sum(axis=1) # ผลรวมแนว row 

In [68]:
sum
diff
multiply_array
divide_array
# print(col_sum)  
print(row_sum)


[2 4]


## 5. Printing arrays

เราสามารถตั้งค่าการพิมพ์อาเรย์ เช่น จำนวนทศนิยม และการย่อค่าได้ด้วย `np.set_printoptions()`

In [ ]:
# np.set_printoptions(precision, suppress)  
# precision: dataType:int default: 8  กำหนดทศนิยม 
# suppress:  dataType: Bool default: False  แสดงผลในรูปแบบวิทยาศาสตร์  True จะกำหนดให้ใช้ ทศนิยม 

np.set_printoptions()  
# np.set_printoptions(precision=2, suppress=True)  
arr = np.random.rand(4,4)
print(arr)


## 3. Basic operations

การบวก (+) ลบ(-) คูณ(*) หาร(/) ระหว่างอาเรย์และกับสเกลาร์สามารถทำได้โดยตรง

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("a + b =", a + b)
print("a * 10 =", a * 10)
print("a ** 2 =", a ** 2)
print("b/2", b/2)


In [ ]:
# a + b 
print("a + b =", a + b)
# a * 10 
print("a * 10 =", a * 10)
# a^2
print("a ** 2 =", a ** 2)
# b / 2 
print("b/2", b/2)

## 4. Indexing, slicing and iterating

การเข้าถึงข้อมูล: 

arr[i],  ตำแหน่งของข้อมูล ใน index ที่ i 

arr[i,j]  สร้าง Array จากจาก array เดิม ในตำแหน่งข้อมูลที่ i ถึง ก่อน j 

การ slicing: arr[1:4], arr[:,1]

การวนลูปด้วย for

In [57]:
a = np.arange(10)
b = np.array([[1,2,3],[4,5,6]])
print("a: ", a)
print("b: ",b)   # print("b: \n",b)  

a:  [0 1 2 3 4 5 6 7 8 9]
b:  [[1 2 3]
 [4 5 6]]


In [ ]:
# Slice array index:2 to index: 6  [2,3,4,5,6]
print(a[2:7])  # slice
# slice row 
for row in b:
    print(row)


[2 3 4 5 6]
[1 2 3]
[4 5 6]


## 5. Shape manipulation 

Changing the shape of an array

In [ ]:
arr = np.arange(12)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# 3 row 4 columns 
print(arr.reshape(3,4))  
# 4 row 3 columns 
print(arr.reshape(4,3) )
# 6 rows 2 columns 
print(arr.reshape(6,2) )

# Transpose Array 
print(arr.reshape(6,2).T)


## 6. Stacking together different arrays

np.vstack: ต่อ Array ในแนวตั้ง

np.hstack: ต่อ Array ในแนวนอน 


In [ ]:
a = np.ones((2,2))
b = np.zeros((2,2))
print(a)
print(b)

In [ ]:
print(np.vstack((a,b))) # ต่อแนวตั้ง  V: vertical
print(np.hstack((a,b))) # ต่อแนวนอน h: horizontal 

## 7. Splitting one array into several smaller ones

้np.hsplit(array, numbers)

np.vsplit(array, numbers)  # ตาม dimension เดิม

In [83]:
arr_split = np.arange((24)).reshape(3,8)
print(arr_split)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [ ]:
# หาผลรวมในแนวตั้ง  
print(arr_split.sum(axis=0))
# หาผลรวมในแนวนอน 
print(arr_split.sum(axis=1))
# np.vsplit(arr_split,3) 

# print(np.vsplit(arr_split,2))
# print(np.hsplit(arr_split,3))

[24 27 30 33 36 39 42 45]
[ 28  92 156]


[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]])]

## 8. Copies and views

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [29]:
b = a.view()  # view
c = a.copy()  # copy
print(c)

[0 1 2 3 4 5]


## 9. Advanced indexing & boolean indexing

In [31]:
arr_advance = np.arange(10)
print(arr_advance)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
print(arr[[1,3,5]])        # index list
print(arr[arr > 5])        # boolean indexing

[1 3 5]
[ 6  7  8  9 10 11]


## Practice 

แบบฝึกหัด NumPy – การสร้างและใช้งานอาเรย์
1. สร้างอาเรย์ 1 มิติ (1D array)
สร้างอาเรย์ ขนาด 8 ที่มีค่าเป็น เลขคี่ จาก 1 ถึง 15 โดยใช้ np.arange()

2. สร้างอาเรย์ 2 มิติ (2D array)
สร้างอาเรย์ 3 แถว 5 คอลัมน์ ที่มีค่าเริ่มต้นทั้งหมดเป็น 9 โดยใช้ฟังก์ชันที่เหมาะสม (np.full() หรือวิธีอื่น)

3. สร้างอาเรย์ 3 มิติ (3D array)
สร้างอาเรย์ 2 × 3 × 4 ที่มีค่าเป็น 0 ทั้งหมด โดยใช้ np.zeros() และตรวจสอบ shape ของอาเรย์นั้น

4. การใช้ np.linspace()
สร้างอาเรย์ที่มี 10 ค่า ซึ่งกระจายจาก 0 ถึง 5 แบบมีช่วงเท่ากันทุกตำแหน่ง

แบบฝึกหัด: NumPy Indexing & Slicing
default_array = np.array([1,2,3,4,5,6])
default_array_2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
1. เลือกสมาชิกตัวสุดท้าย ของ default_array โดยใช้ index  โดยสร้างตัวแปรชื่อ last_item เพื่อรับค่า 

2. เลือกสมาชิกตั้งแต่ตำแหน่งที่ 2 ถึง 4 (index 1–3) ของ default_array โดยสร้างตัวแปรชื่อ slice_2_to_4 เพื่อรับค่า 

3. เลือกค่าทั้งหมดในคอลัมน์ที่ 2 ของ default_array_2d   โดยสร้างตัวแปรชื่อ column_2 hint [:, 1]

4. เลือกค่าในแถวแรก 2 ตัวสุดท้าย ของ default_array_2d โดยสร้างตัวแปรชื่อ row1_last2 เพื่อรับค่า

5. เลือกค่าที่อยู่มุมขวาล่าง (แถวสุดท้าย คอลัมน์สุดท้าย) ของ default_array_2d  โดยสร้างตัวแปรชื่อ bottom_right เพื่อรับค่า 

**แบบฝึกหัด 3:**

- คำนวณ `(x^2 + 2x)` เมื่อ `x = [1,2,3,4]`

## การส่งงาน 

1. ให้สร้าง ไฟล์ ชื่อ exercise_numpy.ipynb ใน โฟลเดอร์ Numpy

2. เมื่อทำเสร็จแล้วให้ push ขึ้น git